#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(
  CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P
)"
export CASUAL_REVIEW_ROOT=$ROOT_DIR

cd "$ROOT_DIR"

tmp=

cleanup() {
  if [[ -n "$tmp" ]]; then
    rm -rf -- "$tmp"
  fi
}

trap cleanup EXIT

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

write_review() {
  local file=$1
  local commit=$2
  local title=$3

  mkdir -p "$(dirname -- "$file")"
  cat >"$file" <<EOF_REVIEW
# Commit review

## Commit

- Commit: \`$commit\`
- Parent: \`1111111111111111111111111111111111111111\`
- Subject: Add browser upload

## Findings

### [Major] $title

- Confidence: High
- Location: \`bin/tool:42-45\`
- Introduced by this commit: Yes
- Gerrit action: Must fix

Suggested Gerrit comment:

> Please reject empty input before sending the request.

## Questions

None.

## Review verdict

Needs changes

The missing validation is a trust-boundary issue.
EOF_REVIEW
}

tmp=$(mktemp -d)
reviews=$tmp/ai-reviews
out=$tmp/out
commit=0123456789abcdef0123456789abcdef01234567
write_review "$reviews/codex/001-0123456789ab.md" "$commit" "Validate input"
write_review "$reviews/claude/001-0123456789ab.md" "$commit" "Validate input"

CASUAL_REVIEW_ENGINE=missing \
GERRIT_LABELS_JSON='{"Needs changes":{"Code-Review":-1}}' \
bin/casual-review gerrit export \
  --output "$out" --engine codex "$reviews" \
  >/dev/null

bundle=$out/0123456.json.gz
[[ -f "$bundle" ]] || die "export test: bundle was not written"
decoded=$tmp/bundle.json
gzip -dc "$bundle" >"$decoded"
jq -e '
  .schema == "casual-review.gerrit-upload.v1"
  and .commit == "0123456789abcdef0123456789abcdef01234567"
  and .commit_short == "0123456"
  and .tag == "autogenerated:casual-review"
  and .notify == "NONE"
  and .summary.review_count == 1
  and .summary.comment_count == 1
  and .summary.verdict_count == 1
  and .reviews[0].engine == "codex"
  and .reviews[0].labels["Code-Review"] == -1
  and .reviews[0].comments[0].path == "bin/tool"
  and .reviews[0].comments[0].line == 42
  and .reviews[0].comments[0].unresolved == true
  and (.reviews[0].comments[0].message | contains("**Confidence:** High"))
  and (.reviews[0].message | contains("**Verdict:** Needs changes"))
' >/dev/null "$decoded" || die "export test: bundle JSON failed"

env_out=$tmp/env-out
CASUAL_REVIEW_ENGINE=codex \
  bin/casual-review gerrit export --output "$env_out" "$reviews" \
  >/dev/null
gzip -dc "$env_out/0123456.json.gz" |
  jq -e '
    .summary.review_count == 1
    and .reviews[0].engine == "codex"
  ' >/dev/null || die "export test: environment engine filter failed"

all_out=$tmp/all-out
CASUAL_REVIEW_ENGINE=missing \
  bin/casual-review gerrit export \
    --output "$all_out" --engine all "$reviews" >/dev/null
gzip -dc "$all_out/0123456.json.gz" |
  jq -e '.summary.review_count == 2' >/dev/null ||
  die "export test: CLI all-engine filter failed"

env_all_out=$tmp/env-all-out
CASUAL_REVIEW_ENGINE=all \
  bin/casual-review gerrit export \
    --output "$env_all_out" "$reviews" >/dev/null
gzip -dc "$env_all_out/0123456.json.gz" |
  jq -e '.summary.review_count == 2' >/dev/null ||
  die "export test: environment all-engine filter failed"

(
  # shellcheck source=../libexec/casual-review/gerrit/export
  # shellcheck disable=SC1091
  source "$ROOT_DIR/libexec/casual-review/gerrit/export"

  TMP_DIR=$tmp/append-failure
  mkdir -p "$TMP_DIR"
  create_bundle "$commit"
  bundle_file=${BUNDLE_FILES[$BUNDLE_INDEX]}
  before=$(cat "$bundle_file")
  if append_review_to_bundle "$BUNDLE_INDEX" '{not-json' 2>/dev/null; then
    die "export test: invalid append JSON succeeded"
  fi
  after=$(cat "$bundle_file")
  [[ "$after" == "$before" ]] ||
    die "export test: failed append clobbered bundle"
  [[ ! -e "$TMP_DIR/update.json" ]] ||
    die "export test: failed append left update file"
)

(
  # shellcheck source=../libexec/casual-review/gerrit/export
  # shellcheck disable=SC1091
  source "$ROOT_DIR/libexec/casual-review/gerrit/export"

  TMP_DIR=$tmp/create-failure
  mkdir -p "$TMP_DIR"
  # shellcheck disable=SC2329
  jq() {
    printf partial
    return 1
  }
  if create_bundle "$commit" >/dev/null 2>&1; then
    die "export test: invalid create succeeded"
  fi
  [[ ${#BUNDLE_FILES[@]} -eq 0 ]] ||
    die "export test: failed create registered bundle"
  [[ ! -e "$TMP_DIR/0123456.json" ]] ||
    die "export test: failed create left bundle file"
)

(
  # shellcheck source=../libexec/casual-review/gerrit/export
  # shellcheck disable=SC1091
  source "$ROOT_DIR/libexec/casual-review/gerrit/export"

  TMP_DIR=$tmp/write-failure
  OUTPUT_DIR=$tmp/write-out
  mkdir -p "$TMP_DIR" "$OUTPUT_DIR"
  printf '{"ok":true}' >"$TMP_DIR/0123456.json"
  printf old >"$OUTPUT_DIR/0123456.json.gz"
  BUNDLE_FILES=("$TMP_DIR/0123456.json")
  # shellcheck disable=SC2034
  BUNDLE_SHORTS=(0123456)
  # shellcheck disable=SC2329
  gzip() {
    printf partial
    return 1
  }
  if write_bundles >/dev/null 2>&1; then
    die "export test: failed gzip write succeeded"
  fi
  [[ "$(cat "$OUTPUT_DIR/0123456.json.gz")" == old ]] ||
    die "export test: failed gzip write clobbered output"
  [[ ! -e "$OUTPUT_DIR/0123456.json.gz.tmp" ]] ||
    die "export test: failed gzip write left temp"
)

(
  # shellcheck disable=SC2031
  cd "$tmp"
"$ROOT_DIR/bin/casual-review" gerrit export --engine codex >/dev/null
) || die "export test: default review directory failed"
[[ -f "$reviews/gerrit-browser-upload/0123456.json.gz" ]] ||
  die "export test: default output bundle missing"
if (
  # shellcheck disable=SC2031
  cd "$tmp"
"$ROOT_DIR/bin/casual-review" gerrit export \
  --engine codex "" >/dev/null 2>&1
); then
  die "export test: explicit empty review directory accepted"
fi

# shellcheck disable=SC2031
limit_out=$tmp/limit-out
write_review \
  "$reviews/codex/002-aaaaaaaaaaaa.md" \
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \
  "Second review"
bin/casual-review gerrit export \
  --output "$limit_out" --limit 1 "$reviews" \
  >/dev/null
[[ -f "$limit_out/0123456.json.gz" ]] ||
  die "export test: limited first bundle missing"
[[ ! -e "$limit_out/aaaaaaa.json.gz" ]] ||
  die "export test: --limit exported too many bundles"

if bin/casual-review gerrit export \
  --limit bad "$reviews" >/dev/null 2>&1; then
  die "export test: invalid limit accepted"
fi

# shellcheck disable=SC2031
collision=$tmp/collision
write_review \
  "$collision/codex/001-012345600000.md" \
  0123456000000000000000000000000000000000 \
  "First collision"
write_review \
  "$collision/codex/002-0123456fffff.md" \
  0123456fffffffffffffffffffffffffffffffff \
  "Second collision"
if bin/casual-review gerrit export "$collision" >/dev/null 2>&1; then
  die "export test: short commit collision accepted"
fi

printf 'Gerrit export test ok\n'
