#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(
  CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P
)"

# shellcheck source=../bin/upload-gerrit-reviews
# shellcheck disable=SC1091
source "$ROOT_DIR/bin/upload-gerrit-reviews"

tmp=

test_cleanup() {
  cleanup
  if [[ -n "$tmp" ]]; then
    rm -rf -- "$tmp"
  fi
}

trap test_cleanup EXIT

validate_common_env

tmp=$(mktemp -d)
dir="$tmp/ai-reviews/codex"
mkdir -p "$dir"
file="$dir/001-0123456789ab.md"
cat >"$file" <<'EOF_REVIEW'
# Commit review

## Commit

- Commit: `0123456789abcdef0123456789abcdef01234567`
- Parent: `1111111111111111111111111111111111111111`
- Subject: Add upload script

## Summary

Adds a script.

## Findings

### [Major] Validate input

- Confidence: High
- Location: `bin/tool:42-45`, `bin/other:8`
- Introduced by this commit: Yes
- Gerrit action: Must fix

Suggested Gerrit comment:

> Please reject empty input before sending the request.

### [Minor] Update docs

- Confidence: Medium
- Location: `README.md`
- Introduced by this commit: Yes
- Gerrit action: Consider

Suggested Gerrit comment:

> Explain the new mode in the README.

## Questions

None.

## Positive observations

None.

## Review verdict

Needs changes

The missing validation is a trust-boundary issue.
EOF_REVIEW

parse_review_file "$file"
[[ "$REVIEW_COMMIT" == 0123456789abcdef0123456789abcdef01234567 ]] ||
  die "upload test: commit parse failed"
[[ "$REVIEW_VERDICT" == "Needs changes" ]] ||
  die "upload test: verdict parse failed"
[[ ${#COMMENT_PATHS[@]} -eq 2 ]] ||
  die "upload test: comment count failed"
[[ "${COMMENT_PATHS[0]}" == "bin/tool" ]] ||
  die "upload test: comment path failed"
[[ "${COMMENT_LINES[0]}" == 42 ]] ||
  die "upload test: comment line failed"
[[ "${COMMENT_MESSAGES[0]}" == \
  "Please reject empty input before sending the request." ]] ||
  die "upload test: comment text failed"
[[ "${COMMENT_PATHS[1]}" == "README.md" ]] ||
  die "upload test: file-level comment path failed"
[[ -z "${COMMENT_LINES[1]}" ]] ||
  die "upload test: file-level comment line failed"

(
  cd "$tmp"
  "$ROOT_DIR/bin/upload-gerrit-reviews" --dry-run >/dev/null
) || die "upload test: default review directory failed"
if (
  cd "$tmp"
  "$ROOT_DIR/bin/upload-gerrit-reviews" --dry-run "" >/dev/null 2>&1
); then
  die "upload test: explicit empty review directory accepted"
fi

initialize_acceptance
comments_json=$(build_comments_json)
export GERRIT_LABELS_JSON='{"Needs changes":{"Code-Review":-1}}'
labels_json=$(labels_for_verdict "$REVIEW_VERDICT")
message=$(build_review_message)
payload=$(build_review_json "$comments_json" "$labels_json" "$message")
jq -e '
  .labels["Code-Review"] == -1
  and .comments["bin/tool"][0].line == 42
  and (.comments["bin/tool"][0].message | contains("**Confidence:**"))
  and (
    .comments["bin/tool"][0].message |
    contains("**Commit:** `0123456`")
  )
  and (.comments["README.md"][0] | has("line") | not)
  and (.message | contains("**Verdict:** Needs changes"))
  and (.message | contains("Needs changes"))
' >/dev/null <<<"$payload" || die "upload test: payload failed"

comments_json=$(
  jq -c -n --arg message "$(format_comment 0)" '
    {"bin/tool": [{id: "c1", line: 42, message: $message}]}
  '
)
filter_duplicate_comments "$comments_json"
[[ "${ACCEPT_COMMENTS[0]}" == 0 ]] ||
  die "upload test: duplicate inline comment not filtered"
[[ "${ACCEPT_COMMENTS[1]}" == 1 ]] ||
  die "upload test: wrong inline comment filtered"

review_message_already_posted \
  "$(jq -c -n --arg message "Patch Set 1:

$message

Code-Review-1" '
    [{tag: "autogenerated:casual-review", message: $message}]
  ')" \
  "$(review_message_marker "$REVIEW_ENGINE" "${REVIEW_COMMIT:0:7}")" \
  "$REVIEW_VERDICT" ||
  die "upload test: duplicate review message not detected"

tui_label_split "The overall design is sound: keep this as prose."
[[ -z "$TUI_LABEL" ]] || die "upload test: prose label false-positive"
tui_label_split "**Confidence:** High"
[[ "$TUI_LABEL" == "Confidence:" ]] ||
  die "upload test: bold label parse failed"

create_curl_auth_config "reviewer" 'p"a\ss'
auth_config=$CURL_AUTH_CONFIG
auth_content=$(cat "$auth_config")
[[ "$auth_content" == 'user = "reviewer:p\"a\\ss"' ]] ||
  die "upload test: curl auth config escaping failed"
auth_mode=$(file_mode "$auth_config") ||
  die "upload test: curl auth config mode check failed"
[[ "$auth_mode" == 600 ]] ||
  die "upload test: curl auth config mode is $auth_mode"
cleanup
[[ ! -e "$auth_config" ]] ||
  die "upload test: curl auth config cleanup failed"

unset GERRIT_CONNECT_TIMEOUT GERRIT_MAX_TIME
validate_curl_timeouts
[[ "${CURL_TIMEOUT_ARGS[*]}" == "--connect-timeout 10 --max-time 120" ]] ||
  die "upload test: default curl timeouts failed"
GERRIT_CONNECT_TIMEOUT=3 GERRIT_MAX_TIME=4 validate_curl_timeouts
[[ "${CURL_TIMEOUT_ARGS[*]}" == "--connect-timeout 3 --max-time 4" ]] ||
  die "upload test: custom curl timeouts failed"
(
  GERRIT_CONNECT_TIMEOUT=0 validate_curl_timeouts
) >/dev/null 2>&1 &&
  die "upload test: invalid connect timeout accepted"
(
  GERRIT_MAX_TIME=abc validate_curl_timeouts
) >/dev/null 2>&1 &&
  die "upload test: invalid max-time accepted"
unset GERRIT_CONNECT_TIMEOUT GERRIT_MAX_TIME

printf 'upload-gerrit-reviews test ok\n'
